name: Docker Security

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  hadolint:
    name: Hadolint
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Dockerfile
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true

      - name: Upload Hadolint scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: hadolint-results.sarif
          category: hadolint

  trivy:
    name: Trivy
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: trivy-results.sarif
          category: trivy

  dockle:
    name: Dockle
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Docker build
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: jobfit:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate summary
        if: always()
        run: |
          {
            echo "## Build Results"
            echo "<details>"
            echo "<summary>Image ID: ${{ steps.build.outputs.imageid }}</summary>"
            echo ""
            echo "Digest: ${{ steps.build.outputs.digest }}"
            echo ""
            echo "\`\`\`json"
            echo "${{ steps.build.outputs.metadata }}"
            echo "\`\`\`"
            echo "</details>"
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Run Dockle
        uses: erzz/dockle-action@v1
        with:
          image: jobfit:${{ github.sha }}
          report-format: sarif
          report-name: dockle
          failure-threshold: FATAL
        continue-on-error: true

      - name: Upload Dockle scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: dockle.sarif
          category: dockle
