name: Protocol Buffers

on:
  pull_request:
    paths:
      - 'api/**/*.proto'
      - 'buf.yaml'
      - 'buf.gen.yaml'
      - 'buf.work.yaml'

jobs:
  buf-lint:
    name: Lint Protocol Buffers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - name: Run buf lint
        id: buf-lint
        run: |
          echo "# Protocol Buffer Lint Results :microscope:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## buf lint Output" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          buf lint || true
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Run buf breaking
        id: buf-breaking
        run: |
          echo "## buf breaking Output" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          buf breaking --against ".git#branch=main" || true
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Run buf format
        id: buf-format
        run: |
          echo "## buf format Check" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          buf format -d || true
          echo '```' >> $GITHUB_STEP_SUMMARY

  generate:
    name: Generate Protocol Buffers
    runs-on: ubuntu-latest
    needs: buf-lint
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - uses: bufbuild/buf-lint-action@v1

      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: '.git#branch=main'

      - name: Generate protos
        run: go generate ./...

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: update generated protocol buffer code"
          title: "chore: update generated protocol buffer code"
          body: "This PR updates the generated protocol buffer code."
          branch: "chore/update-proto-gen"
          base: ${{ github.head_ref }}
